### ISSUE TITLE
Tracking events on Google Analytics

### ISSUE THREAD

**Issue by cauealves** [willianjusten/willianjusten.github.io#15]
Sugestão: Efetuar tracking de eventos em algumas ações específicas pelo analytics. 

Ex: 

![captura de tela 2016-04-21 as 22 09 34](https://cloud.githubusercontent.com/assets/7065285/14728719/d156f9c2-080d-11e6-97e1-e574a6d461b8.png)

![captura de tela 2016-04-21 as 22 09 53](https://cloud.githubusercontent.com/assets/7065285/14728720/dd9d7d64-080d-11e6-9734-7663f04c75b0.png)

![captura de tela 2016-04-21 as 22 09 59](https://cloud.githubusercontent.com/assets/7065285/14728724/e5df0826-080d-11e6-987c-acf94fd7cba8.png)

**Comment by willianjusten** [comment]
Cheguei até a pensar em colocar tracking nisso, mas acabei esquecendo. Vou tentar fazer o mais rápido que der.
