### ISSUE TITLE
Incluir Canais de Youtube na Lista

### ISSUE THREAD

**Issue by Lucasktrindade** [willianjusten/willianjusten.github.io#23]
Fala cara, beleza?

Como no Feedly você pode colocar canais do Youtube que segue, acho interessante colocar alguns canais para galera acompanhar pois também tem muito conteúdo bom.Vou colocar abaixo alguns que sigo.

[thenewboston](https://www.youtube.com/user/thenewboston/videos)
[codigofacilito](https://www.youtube.com/user/codigofacilito/videos)
[The Net Ninja](https://www.youtube.com/channel/UCW5YeuERMmlnqo4oq8vwUpg/videos)
[LearnCode.academy](https://www.youtube.com/user/learncodeacademy/videos)
[Nic Raboy](https://www.youtube.com/user/nicraboy/videos)

Alguns Brasileiros:

[Rodrigo Branas](https://www.youtube.com/channel/UCkqOofjb7nl6V8vXrIbGtiQ)
[「 Webschool.io - JavaScript 」](https://www.youtube.com/channel/UCKdo1RaF8gzfhvkOdZv_ojg)
[Loiane Groner](https://www.youtube.com/channel/UCqQn92noBhY9VKQy4xCHPsg)

Valeu!

**Comment by willianjusten** [comment]
Opa Lucas, eu pensei em colocar canais do Youtube mesmo, mas ainda não tinha tido tempo xD

Pow, se quiser criar uma seção do Youtube, eu ficaria bem agradecido. Igual esse cara fez nesse [PR](https://github.com/willianjusten/willianjusten.github.io/pull/19/files)

**Comment by adrianoavelino** [comment]
Bom, eu vejo com frequencia o canal [devtips](https://www.youtube.com/user/DevTipsForDesigners/videos), o que acham? Ele tá com uma serie de css animate muito legal

**Comment by willianjusten** [comment]
Opa, curto esse canal tb, manda PR ae =D

**Comment by willianjusten** [comment]
Aliás, só vou fechar a issue pq esses acima já foram adicionados.
