### ISSUE TITLE
Em qual sessão por?

### ISSUE THREAD

**Issue by gabrielgomesferraz** [willianjusten/willianjusten.github.io#34]
Olá @willianjusten,

Eu acho muito interessante esse site https://enboard.co/frontend/, pois há uma variedade de links para o mundo do Front End, só gostaria de saber em qual sessão colocar um site desse tipo?

**Comment by willianjusten** [comment]
Hum...eu acho que o enboard basicamente agrega os links que eu e outros colocamos no post... Então não sei muito bem onde e como ele caberia...

**Comment by gabrielgomesferraz** [comment]
Você está certo não pensei por esse lado, se eu tiver algum site mais especifico que ainda não estiver no post eu abro um PR, obrigado 👍

**Comment by willianjusten** [comment]
Show
