### ISSUE TITLE
the home page... show wrong

### ISSUE THREAD

**Issue by Xu-Jian** [willianjusten/willianjusten.github.io#35]
![screen shot 2016-10-29 at 13 47 08](https://cloud.githubusercontent.com/assets/8006051/19827481/55838ee8-9dde-11e6-8105-fb166a4b9a2a.png)

i just download your zip file. 
cd to the folder and run : jekyll new . --force
then run:  jekyll server
and i changed nothing....

so the homepage .... become like the picture .
i use your old version and it works well... but the latest version.. 
i don not know it is my computer's problem or something wrong with your code....
Mac 10.11 ..  can you give me some advice ....  your theme is really cool...

the chrome debug error: in main.js:1 ...   just in case that  you con not see the picture clearly...
t:function(){this.items=Array.prototype.slice.call(document.querySelectorAll("#"+this.el.id+" > article")),this.itemsCount=this.items.length,this.itemsRenderedCount=0,this.didScroll=!1;var e=this;e.items.forEach(function(t,n){i(t)&&(e._checkTotalRendered(),cl

**Comment by Xu-Jian** [comment]
hey thanks . i slove the problem by:
fork your theme to my github.  
and then rename the forked theme to myname.github.io.  justlike: xujian.github.io
them down it to my desktop
then bundle install........ then jekyll server...

thanks for your theme .  best wishes to you .

**Comment by willianjusten** [comment]
Ops, I'm sorry for this delay...
And I'll take a look about those issues...
