### ISSUE TITLE
child_process error

### ISSUE THREAD

**Issue by PedrinhoTc** [willianjusten/willianjusten.github.io#36]
E ae Willian blz ?
Então cara, o problema e esse trecho de codigo que nao estou conseguindo entender. Pelo que andei lendo, vi que vc fez isso para gerar os codigos do jekyll automatizados pelo gulp. Até ai acho que esta OK.
O problema é: Toda vez que vou rodar essa task, o gulp gera um erro.

**Codigo manero**
```
cp           = require('child_process');

gulp.task('jekyll-build', function (done) {
	browserSync.notify(messages.jekyllBuild);

       // Esse cara \/ aqui de baixo esta gerando um erro.
	return cp.spawn('bundle', ['exec', 'jekyll build'], {stdio: 'inherit'})
		.on('close', done);
});
```

**Este e o erro.**

```

[23:50:25] Using gulpfile C:\BlogJekyll\BlogDevCreative\gulpfile.js
[23:50:25] Starting 'jekyll-build'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn bundle ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3
```

 O que eu gostaria de saber é como que o child_process funciona... tendo em vista que eu não manjo muito de back-end, estou estudando para isso. hahaha ^^
Agradecido,

**Comment by willianjusten** [comment]
O `child_process` te permite fazer chamadas (`spawn`) de comandos para dentro do seu sistema, para executar arquivos como `.bat` ou outras coisas assim.

Acabei de ver que você está utilizando o meu blog diretamente, só que ele é mais especificado para a minha plataforma, que é o Mac OS, então o comando tá para o meu Mac e não para Windows.

No template que eu fiz para todos usar, eu tive o cuidado de criar essa verificação, você pode ver [aqui nesse Gulpfile](https://github.com/willianjusten/cards-jekyll-template/blob/master/gulpfile.js#L19-L28).

Meu conselho é que você utilize os templates que eu disponibilizo, pois neles você não terá esse tipo de problema. Segue o [template de cards](https://github.com/willianjusten/cards-jekyll-template/) e se quiser o [modelo antigo](https://github.com/willianjusten/will-jekyll-template)
