### ISSUE TITLE
mixed content warning no post making of parte 1

### ISSUE THREAD

**Issue by renatofrota** [willianjusten/willianjusten.github.io#41]
https://willianjusten.com.br/making-of-parte-1/

A imagem do bug dos font-icons tá hospedada em http:// e o browser dá warning de mixed-content.

http://i.stack.imgur.com/vZhku.png

issue bônus: o texto dentro do bloco highlight tá com a numeração das linhas "quebrada".

**Comment by willianjusten** [comment]
Eita! Obrigado por avisar, como eu mudei de Highlighter a pouco tempo, acabei não vendo isso!

**Comment by willianjusten** [comment]
Removi a numeração por enquanto e também já corrigi a imagem. Obrigado por avisar =)
