### ISSUE TITLE
Rolagem no Firefox

### ISSUE THREAD

**Issue by diple** [willianjusten/willianjusten.github.io#6]
Bug no data-scroll.
Quando tem acentos nas tags, series, etc no Firefox não rola até o ID. Procurei para mandar um PR mas não achei nada a respeito. :(

![bug](https://cloud.githubusercontent.com/assets/11538191/11454120/9a09acec-9609-11e5-864d-df4beb002c88.PNG)

**Comment by willianjusten** [comment]
Corrigido, bastava slugificar o data-scroll com o id do elemento, para que ambos ficassem iguais. Confesso que raramente usei essa página, então nem sabia, vlw!

**Comment by diple** [comment]
Resolveu enquanto a Issue ainda tava quentinha. Isso aí!

**Comment by willianjusten** [comment]
E com CI 100% => https://travis-ci.org/willianjusten/willianjusten.github.io
