### ISSUE TITLE
Listagem de posts da página inicial parada em 19 de julho

### ISSUE THREAD

**Issue by charleslcsantos** [willianjusten/willianjusten.github.io#7]
Willian, fui procurar uma postagem recente sua e vi que na página inicial só mostra os posts até 19 de julho ;)
só isso mesmo... :)

**Comment by willianjusten** [comment]
Ué cara, certeza? =o
Aqui eu consigo ver todos os posts, desde quando comecei o blog, dia 03 de janeiro 2015... Tenta dar um refresh, talvez sua internet ficou instável, sei lá...

**Comment by charleslcsantos** [comment]
Eu consigo ver desde janeiro tambem, só não vejo os atuais.
ele parou de mostrar os novos e só mostra até 19 de julho.

**Comment by willianjusten** [comment]
Ué... que estranho, aqui tem tudo. Segue o print mais longo da história ahuahuahua

![willianjusten-site](https://cloud.githubusercontent.com/assets/3991845/11812146/4a0a6086-a321-11e5-95c5-412a25c4bc56.png)

**Comment by charleslcsantos** [comment]
hahahaha 
Tranquilo..deve ser algum problema aqui mesmo.
;) deve ser o cache..
Valeu man, abraço!

**Comment by willianjusten** [comment]
Está em qual navegador? Já tentou usar outro navegador? Algum refresh, sei lá...

**Comment by charleslcsantos** [comment]
Era o cache...estão aparecendo todos os posts agora.

**Comment by willianjusten** [comment]
Show =)
O Github para não ter problemas de grandes porradas, ele cacheia todo e qualquer site hospedado no pages. Como é um site estático, ou seja, sem chamada de bancos e etc. Acaba que você vê o último estado as vezes.

Bom, vou fechar aqui então.
